#!/bin/bash
set -e

RED='\033[0;31m'
NC='\033[0m'

DC="docker compose"

case "$1" in
  up) $DC up "${@:2}";;
  stop) $DC stop;;
  down) $DC down "${@:2}";;
  ps) $DC ps;;
  build) $DC build "${@:2}" && docker image prune -f;;
  auth | core) "./$1/ape" "${@:2}";;
  "") echo -e "${RED}Command wasn't passed${NC}" && exit 1;;
  *) echo -e "${RED}There is no command {$1}${NC}" && exit 1;;
esac
