#!/bin/bash
set -e

RED='\033[0;31m'
NC='\033[0m'

DC="docker compose"
DC_TEST="docker compose --progress quiet -f docker-compose.yml -f test.docker-compose.yml"

case "$1" in
  up) $DC up "${@:2}";;
  stop) $DC stop;;
  down) $DC down "${@:2}";;
  ps) $DC ps;;
  build) $DC build "${@:2}" && docker image prune -f;;
  auth)
    case "$2" in
      bash | b) $DC run --rm -it auth bash;;
      run | r) $DC --progress quiet run --rm auth "${@:3}";;
      test | t) $DC_TEST run --rm auth go test ./...;;
      "") echo -e "${RED}Auth command wasn't passed${NC}" && exit 1;;
      *) echo -e "${RED}There is no auth command {$2}${NC}" && exit 1;;
    esac
    ;;
  core)
    case "$2" in
      bash | b) $DC run --rm -it core bash;;
      run | r) $DC --progress quiet run --rm core "${@:3}";;
      "") echo -e "${RED}Core command wasn't passed${NC}" && exit 1;;
      *) echo -e "${RED}There is no core command {$2}${NC}" && exit 1;;
    esac
    ;;
  "") echo -e "${RED}Command wasn't passed${NC}" && exit 1;;
  *) echo -e "${RED}There is no command {$1}${NC}" && exit 1;;
esac
