#!/bin/bash
set -e

RED='\033[0;31m'
NC='\033[0m'

DC="docker compose"
DC_TEST="docker compose --progress quiet -f docker-compose.yml -f test.docker-compose.yml"

case "$1" in
  bash | b) $DC run --rm -it auth bash;;
  run | r) $DC --progress quiet run --rm auth "${@:2}";;
  test | t) $DC_TEST run --rm auth go test ./...;;
  "") echo -e "${RED}Auth command wasn't passed${NC}" && exit 1;;
  *) echo -e "${RED}There is no auth command {$1}${NC}" && exit 1;;
esac
